from typing import Protocol

from app.domain.models import Account, Profile, Session


class AccountRepository(Protocol):
    def create(self, account: Account) -> None: ...

    def get_by_email(self, email: str) -> Account | None: ...

    def get_by_id(self, account_id: str) -> Account | None: ...

    def update(self, account: Account) -> None: ...


class SessionRepository(Protocol):
    def create(self, session: Session) -> None: ...

    def get_by_id(self, session_id: str) -> Session | None: ...

    def update(self, session: Session) -> None: ...


class ProfileRepository(Protocol):
    def create(self, profile: Profile) -> None: ...

    def list_by_account_id(self, account_id: str) -> list[Profile]: ...

    def get_by_id(self, profile_id: str) -> Profile | None: ...

    def get_by_name(self, account_id: str, name: str) -> Profile | None: ...

    def count_by_account_id(self, account_id: str) -> int: ...

    def update(self, profile: Profile) -> None: ...

    def delete(self, profile_id: str) -> None: ...

    def set_pin(self, profile_id: str, pin_hash: str | None) -> None: ...

    def get_pin_hash(self, profile_id: str) -> str | None: ...

    def set_control_parental(self, profile_id: str, nivel: str | None) -> None: ...

    def get_control_parental(self, profile_id: str) -> str | None: ...
