// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: catalogo/v1/catalogo.proto

package catalogov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TipoContenido int32

const (
	TipoContenido_TIPO_CONTENIDO_UNSPECIFIED TipoContenido = 0
	TipoContenido_TIPO_CONTENIDO_PELICULA    TipoContenido = 1
	TipoContenido_TIPO_CONTENIDO_SERIE       TipoContenido = 2
)

// Enum value maps for TipoContenido.
var (
	TipoContenido_name = map[int32]string{
		0: "TIPO_CONTENIDO_UNSPECIFIED",
		1: "TIPO_CONTENIDO_PELICULA",
		2: "TIPO_CONTENIDO_SERIE",
	}
	TipoContenido_value = map[string]int32{
		"TIPO_CONTENIDO_UNSPECIFIED": 0,
		"TIPO_CONTENIDO_PELICULA":    1,
		"TIPO_CONTENIDO_SERIE":       2,
	}
)

func (x TipoContenido) Enum() *TipoContenido {
	p := new(TipoContenido)
	*p = x
	return p
}

func (x TipoContenido) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TipoContenido) Descriptor() protoreflect.EnumDescriptor {
	return file_catalogo_v1_catalogo_proto_enumTypes[0].Descriptor()
}

func (TipoContenido) Type() protoreflect.EnumType {
	return &file_catalogo_v1_catalogo_proto_enumTypes[0]
}

func (x TipoContenido) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TipoContenido.Descriptor instead.
func (TipoContenido) EnumDescriptor() ([]byte, []int) {
	return file_catalogo_v1_catalogo_proto_rawDescGZIP(), []int{0}
}

type TipoReaccion int32

const (
	TipoReaccion_TIPO_REACCION_UNSPECIFIED TipoReaccion = 0
	TipoReaccion_TIPO_REACCION_LIKE        TipoReaccion = 1
	TipoReaccion_TIPO_REACCION_DISLIKE     TipoReaccion = 2
)

// Enum value maps for TipoReaccion.
var (
	TipoReaccion_name = map[int32]string{
		0: "TIPO_REACCION_UNSPECIFIED",
		1: "TIPO_REACCION_LIKE",
		2: "TIPO_REACCION_DISLIKE",
	}
	TipoReaccion_value = map[string]int32{
		"TIPO_REACCION_UNSPECIFIED": 0,
		"TIPO_REACCION_LIKE":        1,
		"TIPO_REACCION_DISLIKE":     2,
	}
)

func (x TipoReaccion) Enum() *TipoReaccion {
	p := new(TipoReaccion)
	*p = x
	return p
}

func (x TipoReaccion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TipoReaccion) Descriptor() protoreflect.EnumDescriptor {
	return file_catalogo_v1_catalogo_proto_enumTypes[1].Descriptor()
}

func (TipoReaccion) Type() protoreflect.EnumType {
	return &file_catalogo_v1_catalogo_proto_enumTypes[1]
}

func (x TipoReaccion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TipoReaccion.Descriptor instead.
func (TipoReaccion) EnumDescriptor() ([]byte, []int) {
	return file_catalogo_v1_catalogo_proto_rawDescGZIP(), []int{1}
}

type Genero struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Descripcion   string                 `protobuf:"bytes,3,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genero) Reset() {
	*x = Genero{}
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genero) ProtoMessage() {}

func (x *Genero) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genero.ProtoReflect.Descriptor instead.
func (*Genero) Descriptor() ([]byte, []int) {
	return file_catalogo_v1_catalogo_proto_rawDescGZIP(), []int{0}
}

func (x *Genero) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Genero) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Genero) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

type MiembroReparto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NombreArtistico string                 `protobuf:"bytes,2,opt,name=nombre_artistico,json=nombreArtistico,proto3" json:"nombre_artistico,omitempty"`
	NombreReal      string                 `protobuf:"bytes,3,opt,name=nombre_real,json=nombreReal,proto3" json:"nombre_real,omitempty"`
	Nacionalidad    string                 `protobuf:"bytes,4,opt,name=nacionalidad,proto3" json:"nacionalidad,omitempty"`
	Personaje       string                 `protobuf:"bytes,5,opt,name=personaje,proto3" json:"personaje,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MiembroReparto) Reset() {
	*x = MiembroReparto{}
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiembroReparto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiembroReparto) ProtoMessage() {}

func (x *MiembroReparto) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiembroReparto.ProtoReflect.Descriptor instead.
func (*MiembroReparto) Descriptor() ([]byte, []int) {
	return file_catalogo_v1_catalogo_proto_rawDescGZIP(), []int{1}
}

func (x *MiembroReparto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MiembroReparto) GetNombreArtistico() string {
	if x != nil {
		return x.NombreArtistico
	}
	return ""
}

func (x *MiembroReparto) GetNombreReal() string {
	if x != nil {
		return x.NombreReal
	}
	return ""
}

func (x *MiembroReparto) GetNacionalidad() string {
	if x != nil {
		return x.Nacionalidad
	}
	return ""
}

func (x *MiembroReparto) GetPersonaje() string {
	if x != nil {
		return x.Personaje
	}
	return ""
}

type Contenido struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Titulo                  string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Tipo                    TipoContenido          `protobuf:"varint,3,opt,name=tipo,proto3,enum=catalogo.v1.TipoContenido" json:"tipo,omitempty"`
	Sinopsis                string                 `protobuf:"bytes,4,opt,name=sinopsis,proto3" json:"sinopsis,omitempty"`
	Idioma                  string                 `protobuf:"bytes,5,opt,name=idioma,proto3" json:"idioma,omitempty"`
	UrlPortada              string                 `protobuf:"bytes,6,opt,name=url_portada,json=urlPortada,proto3" json:"url_portada,omitempty"`
	FechaLanzamiento        string                 `protobuf:"bytes,7,opt,name=fecha_lanzamiento,json=fechaLanzamiento,proto3" json:"fecha_lanzamiento,omitempty"`
	PorcentajeRecomendacion float64                `protobuf:"fixed64,8,opt,name=porcentaje_recomendacion,json=porcentajeRecomendacion,proto3" json:"porcentaje_recomendacion,omitempty"`
	UrlTrailer              string                 `protobuf:"bytes,9,opt,name=url_trailer,json=urlTrailer,proto3" json:"url_trailer,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Contenido) Reset() {
	*x = Contenido{}
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contenido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contenido) ProtoMessage() {}

func (x *Contenido) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contenido.ProtoReflect.Descriptor instead.
func (*Contenido) Descriptor() ([]byte, []int) {
	return file_catalogo_v1_catalogo_proto_rawDescGZIP(), []int{2}
}

func (x *Contenido) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contenido) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *Contenido) GetTipo() TipoContenido {
	if x != nil {
		return x.Tipo
	}
	return TipoContenido_TIPO_CONTENIDO_UNSPECIFIED
}

func (x *Contenido) GetSinopsis() string {
	if x != nil {
		return x.Sinopsis
	}
	return ""
}

func (x *Contenido) GetIdioma() string {
	if x != nil {
		return x.Idioma
	}
	return ""
}

func (x *Contenido) GetUrlPortada() string {
	if x != nil {
		return x.UrlPortada
	}
	return ""
}

func (x *Contenido) GetFechaLanzamiento() string {
	if x != nil {
		return x.FechaLanzamiento
	}
	return ""
}

func (x *Contenido) GetPorcentajeRecomendacion() float64 {
	if x != nil {
		return x.PorcentajeRecomendacion
	}
	return 0
}

func (x *Contenido) GetUrlTrailer() string {
	if x != nil {
		return x.UrlTrailer
	}
	return ""
}

type DetalleContenido struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Titulo                  string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Tipo                    TipoContenido          `protobuf:"varint,3,opt,name=tipo,proto3,enum=catalogo.v1.TipoContenido" json:"tipo,omitempty"`
	Sinopsis                string                 `protobuf:"bytes,4,opt,name=sinopsis,proto3" json:"sinopsis,omitempty"`
	FichaTecnica            string                 `protobuf:"bytes,5,opt,name=ficha_tecnica,json=fichaTecnica,proto3" json:"ficha_tecnica,omitempty"`
	FechaLanzamiento        string                 `protobuf:"bytes,6,opt,name=fecha_lanzamiento,json=fechaLanzamiento,proto3" json:"fecha_lanzamiento,omitempty"`
	ClasificacionEdad       string                 `protobuf:"bytes,7,opt,name=clasificacion_edad,json=clasificacionEdad,proto3" json:"clasificacion_edad,omitempty"`
	DuracionMinutos         int32                  `protobuf:"varint,8,opt,name=duracion_minutos,json=duracionMinutos,proto3" json:"duracion_minutos,omitempty"`
	Idioma                  string                 `protobuf:"bytes,9,opt,name=idioma,proto3" json:"idioma,omitempty"`
	UrlPortada              string                 `protobuf:"bytes,10,opt,name=url_portada,json=urlPortada,proto3" json:"url_portada,omitempty"`
	UrlTrailer              string                 `protobuf:"bytes,11,opt,name=url_trailer,json=urlTrailer,proto3" json:"url_trailer,omitempty"`
	TotalLikes              int32                  `protobuf:"varint,12,opt,name=total_likes,json=totalLikes,proto3" json:"total_likes,omitempty"`
	TotalDislikes           int32                  `protobuf:"varint,13,opt,name=total_dislikes,json=totalDislikes,proto3" json:"total_dislikes,omitempty"`
	PorcentajeRecomendacion float64                `protobuf:"fixed64,14,opt,name=porcentaje_recomendacion,json=porcentajeRecomendacion,proto3" json:"porcentaje_recomendacion,omitempty"`
	Generos                 []*Genero              `protobuf:"bytes,15,rep,name=generos,proto3" json:"generos,omitempty"`
	Reparto                 []*MiembroReparto      `protobuf:"bytes,16,rep,name=reparto,proto3" json:"reparto,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DetalleContenido) Reset() {
	*x = DetalleContenido{}
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetalleContenido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetalleContenido) ProtoMessage() {}

func (x *DetalleContenido) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetalleContenido.ProtoReflect.Descriptor instead.
func (*DetalleContenido) Descriptor() ([]byte, []int) {
	return file_catalogo_v1_catalogo_proto_rawDescGZIP(), []int{3}
}

func (x *DetalleContenido) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DetalleContenido) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *DetalleContenido) GetTipo() TipoContenido {
	if x != nil {
		return x.Tipo
	}
	return TipoContenido_TIPO_CONTENIDO_UNSPECIFIED
}

func (x *DetalleContenido) GetSinopsis() string {
	if x != nil {
		return x.Sinopsis
	}
	return ""
}

func (x *DetalleContenido) GetFichaTecnica() string {
	if x != nil {
		return x.FichaTecnica
	}
	return ""
}

func (x *DetalleContenido) GetFechaLanzamiento() string {
	if x != nil {
		return x.FechaLanzamiento
	}
	return ""
}

func (x *DetalleContenido) GetClasificacionEdad() string {
	if x != nil {
		return x.ClasificacionEdad
	}
	return ""
}

func (x *DetalleContenido) GetDuracionMinutos() int32 {
	if x != nil {
		return x.DuracionMinutos
	}
	return 0
}

func (x *DetalleContenido) GetIdioma() string {
	if x != nil {
		return x.Idioma
	}
	return ""
}

func (x *DetalleContenido) GetUrlPortada() string {
	if x != nil {
		return x.UrlPortada
	}
	return ""
}

func (x *DetalleContenido) GetUrlTrailer() string {
	if x != nil {
		return x.UrlTrailer
	}
	return ""
}

func (x *DetalleContenido) GetTotalLikes() int32 {
	if x != nil {
		return x.TotalLikes
	}
	return 0
}

func (x *DetalleContenido) GetTotalDislikes() int32 {
	if x != nil {
		return x.TotalDislikes
	}
	return 0
}

func (x *DetalleContenido) GetPorcentajeRecomendacion() float64 {
	if x != nil {
		return x.PorcentajeRecomendacion
	}
	return 0
}

func (x *DetalleContenido) GetGeneros() []*Genero {
	if x != nil {
		return x.Generos
	}
	return nil
}

func (x *DetalleContenido) GetReparto() []*MiembroReparto {
	if x != nil {
		return x.Reparto
	}
	return nil
}

type ListarContenidoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarContenidoRequest) Reset() {
	*x = ListarContenidoRequest{}
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarContenidoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarContenidoRequest) ProtoMessage() {}

func (x *ListarContenidoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarContenidoRequest.ProtoReflect.Descriptor instead.
func (*ListarContenidoRequest) Descriptor() ([]byte, []int) {
	return file_catalogo_v1_catalogo_proto_rawDescGZIP(), []int{4}
}

type ListarContenidoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contenidos    []*Contenido           `protobuf:"bytes,1,rep,name=contenidos,proto3" json:"contenidos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarContenidoResponse) Reset() {
	*x = ListarContenidoResponse{}
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarContenidoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarContenidoResponse) ProtoMessage() {}

func (x *ListarContenidoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarContenidoResponse.ProtoReflect.Descriptor instead.
func (*ListarContenidoResponse) Descriptor() ([]byte, []int) {
	return file_catalogo_v1_catalogo_proto_rawDescGZIP(), []int{5}
}

func (x *ListarContenidoResponse) GetContenidos() []*Contenido {
	if x != nil {
		return x.Contenidos
	}
	return nil
}

type BuscarContenidoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuscarContenidoRequest) Reset() {
	*x = BuscarContenidoRequest{}
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuscarContenidoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuscarContenidoRequest) ProtoMessage() {}

func (x *BuscarContenidoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuscarContenidoRequest.ProtoReflect.Descriptor instead.
func (*BuscarContenidoRequest) Descriptor() ([]byte, []int) {
	return file_catalogo_v1_catalogo_proto_rawDescGZIP(), []int{6}
}

func (x *BuscarContenidoRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type FiltrarContenidoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GeneroIds     []int64                `protobuf:"varint,1,rep,packed,name=genero_ids,json=generoIds,proto3" json:"genero_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FiltrarContenidoRequest) Reset() {
	*x = FiltrarContenidoRequest{}
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FiltrarContenidoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FiltrarContenidoRequest) ProtoMessage() {}

func (x *FiltrarContenidoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FiltrarContenidoRequest.ProtoReflect.Descriptor instead.
func (*FiltrarContenidoRequest) Descriptor() ([]byte, []int) {
	return file_catalogo_v1_catalogo_proto_rawDescGZIP(), []int{7}
}

func (x *FiltrarContenidoRequest) GetGeneroIds() []int64 {
	if x != nil {
		return x.GeneroIds
	}
	return nil
}

type ObtenerDetalleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContenidoId   string                 `protobuf:"bytes,1,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObtenerDetalleRequest) Reset() {
	*x = ObtenerDetalleRequest{}
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtenerDetalleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerDetalleRequest) ProtoMessage() {}

func (x *ObtenerDetalleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerDetalleRequest.ProtoReflect.Descriptor instead.
func (*ObtenerDetalleRequest) Descriptor() ([]byte, []int) {
	return file_catalogo_v1_catalogo_proto_rawDescGZIP(), []int{8}
}

func (x *ObtenerDetalleRequest) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

type ObtenerDetalleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detalle       *DetalleContenido      `protobuf:"bytes,1,opt,name=detalle,proto3" json:"detalle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObtenerDetalleResponse) Reset() {
	*x = ObtenerDetalleResponse{}
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtenerDetalleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerDetalleResponse) ProtoMessage() {}

func (x *ObtenerDetalleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerDetalleResponse.ProtoReflect.Descriptor instead.
func (*ObtenerDetalleResponse) Descriptor() ([]byte, []int) {
	return file_catalogo_v1_catalogo_proto_rawDescGZIP(), []int{9}
}

func (x *ObtenerDetalleResponse) GetDetalle() *DetalleContenido {
	if x != nil {
		return x.Detalle
	}
	return nil
}

type CalificarContenidoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContenidoId   string                 `protobuf:"bytes,1,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	PerfilId      string                 `protobuf:"bytes,2,opt,name=perfil_id,json=perfilId,proto3" json:"perfil_id,omitempty"`
	Reaccion      TipoReaccion           `protobuf:"varint,3,opt,name=reaccion,proto3,enum=catalogo.v1.TipoReaccion" json:"reaccion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalificarContenidoRequest) Reset() {
	*x = CalificarContenidoRequest{}
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalificarContenidoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalificarContenidoRequest) ProtoMessage() {}

func (x *CalificarContenidoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalificarContenidoRequest.ProtoReflect.Descriptor instead.
func (*CalificarContenidoRequest) Descriptor() ([]byte, []int) {
	return file_catalogo_v1_catalogo_proto_rawDescGZIP(), []int{10}
}

func (x *CalificarContenidoRequest) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

func (x *CalificarContenidoRequest) GetPerfilId() string {
	if x != nil {
		return x.PerfilId
	}
	return ""
}

func (x *CalificarContenidoRequest) GetReaccion() TipoReaccion {
	if x != nil {
		return x.Reaccion
	}
	return TipoReaccion_TIPO_REACCION_UNSPECIFIED
}

type CalificarContenidoResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	PorcentajeRecomendacion float64                `protobuf:"fixed64,1,opt,name=porcentaje_recomendacion,json=porcentajeRecomendacion,proto3" json:"porcentaje_recomendacion,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CalificarContenidoResponse) Reset() {
	*x = CalificarContenidoResponse{}
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalificarContenidoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalificarContenidoResponse) ProtoMessage() {}

func (x *CalificarContenidoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalificarContenidoResponse.ProtoReflect.Descriptor instead.
func (*CalificarContenidoResponse) Descriptor() ([]byte, []int) {
	return file_catalogo_v1_catalogo_proto_rawDescGZIP(), []int{11}
}

func (x *CalificarContenidoResponse) GetPorcentajeRecomendacion() float64 {
	if x != nil {
		return x.PorcentajeRecomendacion
	}
	return 0
}

type CrearContenidoRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Titulo            string                 `protobuf:"bytes,1,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Tipo              TipoContenido          `protobuf:"varint,2,opt,name=tipo,proto3,enum=catalogo.v1.TipoContenido" json:"tipo,omitempty"`
	Sinopsis          string                 `protobuf:"bytes,3,opt,name=sinopsis,proto3" json:"sinopsis,omitempty"`
	FichaTecnica      string                 `protobuf:"bytes,4,opt,name=ficha_tecnica,json=fichaTecnica,proto3" json:"ficha_tecnica,omitempty"`
	FechaLanzamiento  string                 `protobuf:"bytes,5,opt,name=fecha_lanzamiento,json=fechaLanzamiento,proto3" json:"fecha_lanzamiento,omitempty"`
	ClasificacionEdad string                 `protobuf:"bytes,6,opt,name=clasificacion_edad,json=clasificacionEdad,proto3" json:"clasificacion_edad,omitempty"`
	DuracionMinutos   int32                  `protobuf:"varint,7,opt,name=duracion_minutos,json=duracionMinutos,proto3" json:"duracion_minutos,omitempty"`
	Idioma            string                 `protobuf:"bytes,8,opt,name=idioma,proto3" json:"idioma,omitempty"`
	UrlPortada        string                 `protobuf:"bytes,9,opt,name=url_portada,json=urlPortada,proto3" json:"url_portada,omitempty"`
	UrlTrailer        string                 `protobuf:"bytes,10,opt,name=url_trailer,json=urlTrailer,proto3" json:"url_trailer,omitempty"`
	CreadoPorCuentaId string                 `protobuf:"bytes,11,opt,name=creado_por_cuenta_id,json=creadoPorCuentaId,proto3" json:"creado_por_cuenta_id,omitempty"`
	GeneroIds         []int64                `protobuf:"varint,12,rep,packed,name=genero_ids,json=generoIds,proto3" json:"genero_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CrearContenidoRequest) Reset() {
	*x = CrearContenidoRequest{}
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearContenidoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearContenidoRequest) ProtoMessage() {}

func (x *CrearContenidoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearContenidoRequest.ProtoReflect.Descriptor instead.
func (*CrearContenidoRequest) Descriptor() ([]byte, []int) {
	return file_catalogo_v1_catalogo_proto_rawDescGZIP(), []int{12}
}

func (x *CrearContenidoRequest) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *CrearContenidoRequest) GetTipo() TipoContenido {
	if x != nil {
		return x.Tipo
	}
	return TipoContenido_TIPO_CONTENIDO_UNSPECIFIED
}

func (x *CrearContenidoRequest) GetSinopsis() string {
	if x != nil {
		return x.Sinopsis
	}
	return ""
}

func (x *CrearContenidoRequest) GetFichaTecnica() string {
	if x != nil {
		return x.FichaTecnica
	}
	return ""
}

func (x *CrearContenidoRequest) GetFechaLanzamiento() string {
	if x != nil {
		return x.FechaLanzamiento
	}
	return ""
}

func (x *CrearContenidoRequest) GetClasificacionEdad() string {
	if x != nil {
		return x.ClasificacionEdad
	}
	return ""
}

func (x *CrearContenidoRequest) GetDuracionMinutos() int32 {
	if x != nil {
		return x.DuracionMinutos
	}
	return 0
}

func (x *CrearContenidoRequest) GetIdioma() string {
	if x != nil {
		return x.Idioma
	}
	return ""
}

func (x *CrearContenidoRequest) GetUrlPortada() string {
	if x != nil {
		return x.UrlPortada
	}
	return ""
}

func (x *CrearContenidoRequest) GetUrlTrailer() string {
	if x != nil {
		return x.UrlTrailer
	}
	return ""
}

func (x *CrearContenidoRequest) GetCreadoPorCuentaId() string {
	if x != nil {
		return x.CreadoPorCuentaId
	}
	return ""
}

func (x *CrearContenidoRequest) GetGeneroIds() []int64 {
	if x != nil {
		return x.GeneroIds
	}
	return nil
}

type ActualizarContenidoRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ContenidoId       string                 `protobuf:"bytes,1,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	Titulo            string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Sinopsis          string                 `protobuf:"bytes,3,opt,name=sinopsis,proto3" json:"sinopsis,omitempty"`
	FichaTecnica      string                 `protobuf:"bytes,4,opt,name=ficha_tecnica,json=fichaTecnica,proto3" json:"ficha_tecnica,omitempty"`
	ClasificacionEdad string                 `protobuf:"bytes,5,opt,name=clasificacion_edad,json=clasificacionEdad,proto3" json:"clasificacion_edad,omitempty"`
	DuracionMinutos   int32                  `protobuf:"varint,6,opt,name=duracion_minutos,json=duracionMinutos,proto3" json:"duracion_minutos,omitempty"`
	UrlPortada        string                 `protobuf:"bytes,7,opt,name=url_portada,json=urlPortada,proto3" json:"url_portada,omitempty"`
	UrlTrailer        string                 `protobuf:"bytes,8,opt,name=url_trailer,json=urlTrailer,proto3" json:"url_trailer,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ActualizarContenidoRequest) Reset() {
	*x = ActualizarContenidoRequest{}
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarContenidoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarContenidoRequest) ProtoMessage() {}

func (x *ActualizarContenidoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarContenidoRequest.ProtoReflect.Descriptor instead.
func (*ActualizarContenidoRequest) Descriptor() ([]byte, []int) {
	return file_catalogo_v1_catalogo_proto_rawDescGZIP(), []int{13}
}

func (x *ActualizarContenidoRequest) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

func (x *ActualizarContenidoRequest) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *ActualizarContenidoRequest) GetSinopsis() string {
	if x != nil {
		return x.Sinopsis
	}
	return ""
}

func (x *ActualizarContenidoRequest) GetFichaTecnica() string {
	if x != nil {
		return x.FichaTecnica
	}
	return ""
}

func (x *ActualizarContenidoRequest) GetClasificacionEdad() string {
	if x != nil {
		return x.ClasificacionEdad
	}
	return ""
}

func (x *ActualizarContenidoRequest) GetDuracionMinutos() int32 {
	if x != nil {
		return x.DuracionMinutos
	}
	return 0
}

func (x *ActualizarContenidoRequest) GetUrlPortada() string {
	if x != nil {
		return x.UrlPortada
	}
	return ""
}

func (x *ActualizarContenidoRequest) GetUrlTrailer() string {
	if x != nil {
		return x.UrlTrailer
	}
	return ""
}

type EliminarContenidoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContenidoId   string                 `protobuf:"bytes,1,opt,name=contenido_id,json=contenidoId,proto3" json:"contenido_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EliminarContenidoRequest) Reset() {
	*x = EliminarContenidoRequest{}
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminarContenidoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarContenidoRequest) ProtoMessage() {}

func (x *EliminarContenidoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarContenidoRequest.ProtoReflect.Descriptor instead.
func (*EliminarContenidoRequest) Descriptor() ([]byte, []int) {
	return file_catalogo_v1_catalogo_proto_rawDescGZIP(), []int{14}
}

func (x *EliminarContenidoRequest) GetContenidoId() string {
	if x != nil {
		return x.ContenidoId
	}
	return ""
}

type EliminarContenidoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EliminarContenidoResponse) Reset() {
	*x = EliminarContenidoResponse{}
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminarContenidoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarContenidoResponse) ProtoMessage() {}

func (x *EliminarContenidoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_v1_catalogo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarContenidoResponse.ProtoReflect.Descriptor instead.
func (*EliminarContenidoResponse) Descriptor() ([]byte, []int) {
	return file_catalogo_v1_catalogo_proto_rawDescGZIP(), []int{15}
}

func (x *EliminarContenidoResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_catalogo_v1_catalogo_proto protoreflect.FileDescriptor

const file_catalogo_v1_catalogo_proto_rawDesc = "" +
	"\n" +
	"\x1acatalogo/v1/catalogo.proto\x12\vcatalogo.v1\"R\n" +
	"\x06Genero\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12 \n" +
	"\vdescripcion\x18\x03 \x01(\tR\vdescripcion\"\xae\x01\n" +
	"\x0eMiembroReparto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12)\n" +
	"\x10nombre_artistico\x18\x02 \x01(\tR\x0fnombreArtistico\x12\x1f\n" +
	"\vnombre_real\x18\x03 \x01(\tR\n" +
	"nombreReal\x12\"\n" +
	"\fnacionalidad\x18\x04 \x01(\tR\fnacionalidad\x12\x1c\n" +
	"\tpersonaje\x18\x05 \x01(\tR\tpersonaje\"\xc1\x02\n" +
	"\tContenido\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12.\n" +
	"\x04tipo\x18\x03 \x01(\x0e2\x1a.catalogo.v1.TipoContenidoR\x04tipo\x12\x1a\n" +
	"\bsinopsis\x18\x04 \x01(\tR\bsinopsis\x12\x16\n" +
	"\x06idioma\x18\x05 \x01(\tR\x06idioma\x12\x1f\n" +
	"\vurl_portada\x18\x06 \x01(\tR\n" +
	"urlPortada\x12+\n" +
	"\x11fecha_lanzamiento\x18\a \x01(\tR\x10fechaLanzamiento\x129\n" +
	"\x18porcentaje_recomendacion\x18\b \x01(\x01R\x17porcentajeRecomendacion\x12\x1f\n" +
	"\vurl_trailer\x18\t \x01(\tR\n" +
	"urlTrailer\"\xf5\x04\n" +
	"\x10DetalleContenido\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12.\n" +
	"\x04tipo\x18\x03 \x01(\x0e2\x1a.catalogo.v1.TipoContenidoR\x04tipo\x12\x1a\n" +
	"\bsinopsis\x18\x04 \x01(\tR\bsinopsis\x12#\n" +
	"\rficha_tecnica\x18\x05 \x01(\tR\ffichaTecnica\x12+\n" +
	"\x11fecha_lanzamiento\x18\x06 \x01(\tR\x10fechaLanzamiento\x12-\n" +
	"\x12clasificacion_edad\x18\a \x01(\tR\x11clasificacionEdad\x12)\n" +
	"\x10duracion_minutos\x18\b \x01(\x05R\x0fduracionMinutos\x12\x16\n" +
	"\x06idioma\x18\t \x01(\tR\x06idioma\x12\x1f\n" +
	"\vurl_portada\x18\n" +
	" \x01(\tR\n" +
	"urlPortada\x12\x1f\n" +
	"\vurl_trailer\x18\v \x01(\tR\n" +
	"urlTrailer\x12\x1f\n" +
	"\vtotal_likes\x18\f \x01(\x05R\n" +
	"totalLikes\x12%\n" +
	"\x0etotal_dislikes\x18\r \x01(\x05R\rtotalDislikes\x129\n" +
	"\x18porcentaje_recomendacion\x18\x0e \x01(\x01R\x17porcentajeRecomendacion\x12-\n" +
	"\ageneros\x18\x0f \x03(\v2\x13.catalogo.v1.GeneroR\ageneros\x125\n" +
	"\areparto\x18\x10 \x03(\v2\x1b.catalogo.v1.MiembroRepartoR\areparto\"\x18\n" +
	"\x16ListarContenidoRequest\"Q\n" +
	"\x17ListarContenidoResponse\x126\n" +
	"\n" +
	"contenidos\x18\x01 \x03(\v2\x16.catalogo.v1.ContenidoR\n" +
	"contenidos\".\n" +
	"\x16BuscarContenidoRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"8\n" +
	"\x17FiltrarContenidoRequest\x12\x1d\n" +
	"\n" +
	"genero_ids\x18\x01 \x03(\x03R\tgeneroIds\":\n" +
	"\x15ObtenerDetalleRequest\x12!\n" +
	"\fcontenido_id\x18\x01 \x01(\tR\vcontenidoId\"Q\n" +
	"\x16ObtenerDetalleResponse\x127\n" +
	"\adetalle\x18\x01 \x01(\v2\x1d.catalogo.v1.DetalleContenidoR\adetalle\"\x92\x01\n" +
	"\x19CalificarContenidoRequest\x12!\n" +
	"\fcontenido_id\x18\x01 \x01(\tR\vcontenidoId\x12\x1b\n" +
	"\tperfil_id\x18\x02 \x01(\tR\bperfilId\x125\n" +
	"\breaccion\x18\x03 \x01(\x0e2\x19.catalogo.v1.TipoReaccionR\breaccion\"W\n" +
	"\x1aCalificarContenidoResponse\x129\n" +
	"\x18porcentaje_recomendacion\x18\x01 \x01(\x01R\x17porcentajeRecomendacion\"\xd1\x03\n" +
	"\x15CrearContenidoRequest\x12\x16\n" +
	"\x06titulo\x18\x01 \x01(\tR\x06titulo\x12.\n" +
	"\x04tipo\x18\x02 \x01(\x0e2\x1a.catalogo.v1.TipoContenidoR\x04tipo\x12\x1a\n" +
	"\bsinopsis\x18\x03 \x01(\tR\bsinopsis\x12#\n" +
	"\rficha_tecnica\x18\x04 \x01(\tR\ffichaTecnica\x12+\n" +
	"\x11fecha_lanzamiento\x18\x05 \x01(\tR\x10fechaLanzamiento\x12-\n" +
	"\x12clasificacion_edad\x18\x06 \x01(\tR\x11clasificacionEdad\x12)\n" +
	"\x10duracion_minutos\x18\a \x01(\x05R\x0fduracionMinutos\x12\x16\n" +
	"\x06idioma\x18\b \x01(\tR\x06idioma\x12\x1f\n" +
	"\vurl_portada\x18\t \x01(\tR\n" +
	"urlPortada\x12\x1f\n" +
	"\vurl_trailer\x18\n" +
	" \x01(\tR\n" +
	"urlTrailer\x12/\n" +
	"\x14creado_por_cuenta_id\x18\v \x01(\tR\x11creadoPorCuentaId\x12\x1d\n" +
	"\n" +
	"genero_ids\x18\f \x03(\x03R\tgeneroIds\"\xb4\x02\n" +
	"\x1aActualizarContenidoRequest\x12!\n" +
	"\fcontenido_id\x18\x01 \x01(\tR\vcontenidoId\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12\x1a\n" +
	"\bsinopsis\x18\x03 \x01(\tR\bsinopsis\x12#\n" +
	"\rficha_tecnica\x18\x04 \x01(\tR\ffichaTecnica\x12-\n" +
	"\x12clasificacion_edad\x18\x05 \x01(\tR\x11clasificacionEdad\x12)\n" +
	"\x10duracion_minutos\x18\x06 \x01(\x05R\x0fduracionMinutos\x12\x1f\n" +
	"\vurl_portada\x18\a \x01(\tR\n" +
	"urlPortada\x12\x1f\n" +
	"\vurl_trailer\x18\b \x01(\tR\n" +
	"urlTrailer\"=\n" +
	"\x18EliminarContenidoRequest\x12!\n" +
	"\fcontenido_id\x18\x01 \x01(\tR\vcontenidoId\"+\n" +
	"\x19EliminarContenidoResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*f\n" +
	"\rTipoContenido\x12\x1e\n" +
	"\x1aTIPO_CONTENIDO_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TIPO_CONTENIDO_PELICULA\x10\x01\x12\x18\n" +
	"\x14TIPO_CONTENIDO_SERIE\x10\x02*`\n" +
	"\fTipoReaccion\x12\x1d\n" +
	"\x19TIPO_REACCION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TIPO_REACCION_LIKE\x10\x01\x12\x19\n" +
	"\x15TIPO_REACCION_DISLIKE\x10\x022\xf9\x05\n" +
	"\x0fCatalogoService\x12\\\n" +
	"\x0fListarContenido\x12#.catalogo.v1.ListarContenidoRequest\x1a$.catalogo.v1.ListarContenidoResponse\x12\\\n" +
	"\x0fBuscarContenido\x12#.catalogo.v1.BuscarContenidoRequest\x1a$.catalogo.v1.ListarContenidoResponse\x12^\n" +
	"\x10FiltrarContenido\x12$.catalogo.v1.FiltrarContenidoRequest\x1a$.catalogo.v1.ListarContenidoResponse\x12Y\n" +
	"\x0eObtenerDetalle\x12\".catalogo.v1.ObtenerDetalleRequest\x1a#.catalogo.v1.ObtenerDetalleResponse\x12e\n" +
	"\x12CalificarContenido\x12&.catalogo.v1.CalificarContenidoRequest\x1a'.catalogo.v1.CalificarContenidoResponse\x12L\n" +
	"\x0eCrearContenido\x12\".catalogo.v1.CrearContenidoRequest\x1a\x16.catalogo.v1.Contenido\x12V\n" +
	"\x13ActualizarContenido\x12'.catalogo.v1.ActualizarContenidoRequest\x1a\x16.catalogo.v1.Contenido\x12b\n" +
	"\x11EliminarContenido\x12%.catalogo.v1.EliminarContenidoRequest\x1a&.catalogo.v1.EliminarContenidoResponseB;Z9quetzaltv/services/catalogo/pkg/pb/catalogo/v1;catalogov1b\x06proto3"

var (
	file_catalogo_v1_catalogo_proto_rawDescOnce sync.Once
	file_catalogo_v1_catalogo_proto_rawDescData []byte
)

func file_catalogo_v1_catalogo_proto_rawDescGZIP() []byte {
	file_catalogo_v1_catalogo_proto_rawDescOnce.Do(func() {
		file_catalogo_v1_catalogo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalogo_v1_catalogo_proto_rawDesc), len(file_catalogo_v1_catalogo_proto_rawDesc)))
	})
	return file_catalogo_v1_catalogo_proto_rawDescData
}

var file_catalogo_v1_catalogo_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_catalogo_v1_catalogo_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_catalogo_v1_catalogo_proto_goTypes = []any{
	(TipoContenido)(0),                 // 0: catalogo.v1.TipoContenido
	(TipoReaccion)(0),                  // 1: catalogo.v1.TipoReaccion
	(*Genero)(nil),                     // 2: catalogo.v1.Genero
	(*MiembroReparto)(nil),             // 3: catalogo.v1.MiembroReparto
	(*Contenido)(nil),                  // 4: catalogo.v1.Contenido
	(*DetalleContenido)(nil),           // 5: catalogo.v1.DetalleContenido
	(*ListarContenidoRequest)(nil),     // 6: catalogo.v1.ListarContenidoRequest
	(*ListarContenidoResponse)(nil),    // 7: catalogo.v1.ListarContenidoResponse
	(*BuscarContenidoRequest)(nil),     // 8: catalogo.v1.BuscarContenidoRequest
	(*FiltrarContenidoRequest)(nil),    // 9: catalogo.v1.FiltrarContenidoRequest
	(*ObtenerDetalleRequest)(nil),      // 10: catalogo.v1.ObtenerDetalleRequest
	(*ObtenerDetalleResponse)(nil),     // 11: catalogo.v1.ObtenerDetalleResponse
	(*CalificarContenidoRequest)(nil),  // 12: catalogo.v1.CalificarContenidoRequest
	(*CalificarContenidoResponse)(nil), // 13: catalogo.v1.CalificarContenidoResponse
	(*CrearContenidoRequest)(nil),      // 14: catalogo.v1.CrearContenidoRequest
	(*ActualizarContenidoRequest)(nil), // 15: catalogo.v1.ActualizarContenidoRequest
	(*EliminarContenidoRequest)(nil),   // 16: catalogo.v1.EliminarContenidoRequest
	(*EliminarContenidoResponse)(nil),  // 17: catalogo.v1.EliminarContenidoResponse
}
var file_catalogo_v1_catalogo_proto_depIdxs = []int32{
	0,  // 0: catalogo.v1.Contenido.tipo:type_name -> catalogo.v1.TipoContenido
	0,  // 1: catalogo.v1.DetalleContenido.tipo:type_name -> catalogo.v1.TipoContenido
	2,  // 2: catalogo.v1.DetalleContenido.generos:type_name -> catalogo.v1.Genero
	3,  // 3: catalogo.v1.DetalleContenido.reparto:type_name -> catalogo.v1.MiembroReparto
	4,  // 4: catalogo.v1.ListarContenidoResponse.contenidos:type_name -> catalogo.v1.Contenido
	5,  // 5: catalogo.v1.ObtenerDetalleResponse.detalle:type_name -> catalogo.v1.DetalleContenido
	1,  // 6: catalogo.v1.CalificarContenidoRequest.reaccion:type_name -> catalogo.v1.TipoReaccion
	0,  // 7: catalogo.v1.CrearContenidoRequest.tipo:type_name -> catalogo.v1.TipoContenido
	6,  // 8: catalogo.v1.CatalogoService.ListarContenido:input_type -> catalogo.v1.ListarContenidoRequest
	8,  // 9: catalogo.v1.CatalogoService.BuscarContenido:input_type -> catalogo.v1.BuscarContenidoRequest
	9,  // 10: catalogo.v1.CatalogoService.FiltrarContenido:input_type -> catalogo.v1.FiltrarContenidoRequest
	10, // 11: catalogo.v1.CatalogoService.ObtenerDetalle:input_type -> catalogo.v1.ObtenerDetalleRequest
	12, // 12: catalogo.v1.CatalogoService.CalificarContenido:input_type -> catalogo.v1.CalificarContenidoRequest
	14, // 13: catalogo.v1.CatalogoService.CrearContenido:input_type -> catalogo.v1.CrearContenidoRequest
	15, // 14: catalogo.v1.CatalogoService.ActualizarContenido:input_type -> catalogo.v1.ActualizarContenidoRequest
	16, // 15: catalogo.v1.CatalogoService.EliminarContenido:input_type -> catalogo.v1.EliminarContenidoRequest
	7,  // 16: catalogo.v1.CatalogoService.ListarContenido:output_type -> catalogo.v1.ListarContenidoResponse
	7,  // 17: catalogo.v1.CatalogoService.BuscarContenido:output_type -> catalogo.v1.ListarContenidoResponse
	7,  // 18: catalogo.v1.CatalogoService.FiltrarContenido:output_type -> catalogo.v1.ListarContenidoResponse
	11, // 19: catalogo.v1.CatalogoService.ObtenerDetalle:output_type -> catalogo.v1.ObtenerDetalleResponse
	13, // 20: catalogo.v1.CatalogoService.CalificarContenido:output_type -> catalogo.v1.CalificarContenidoResponse
	4,  // 21: catalogo.v1.CatalogoService.CrearContenido:output_type -> catalogo.v1.Contenido
	4,  // 22: catalogo.v1.CatalogoService.ActualizarContenido:output_type -> catalogo.v1.Contenido
	17, // 23: catalogo.v1.CatalogoService.EliminarContenido:output_type -> catalogo.v1.EliminarContenidoResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_catalogo_v1_catalogo_proto_init() }
func file_catalogo_v1_catalogo_proto_init() {
	if File_catalogo_v1_catalogo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalogo_v1_catalogo_proto_rawDesc), len(file_catalogo_v1_catalogo_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalogo_v1_catalogo_proto_goTypes,
		DependencyIndexes: file_catalogo_v1_catalogo_proto_depIdxs,
		EnumInfos:         file_catalogo_v1_catalogo_proto_enumTypes,
		MessageInfos:      file_catalogo_v1_catalogo_proto_msgTypes,
	}.Build()
	File_catalogo_v1_catalogo_proto = out.File
	file_catalogo_v1_catalogo_proto_goTypes = nil
	file_catalogo_v1_catalogo_proto_depIdxs = nil
}
