// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: catalogo/v1/catalogo.proto

package catalogov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogoService_ListarContenido_FullMethodName     = "/catalogo.v1.CatalogoService/ListarContenido"
	CatalogoService_BuscarContenido_FullMethodName     = "/catalogo.v1.CatalogoService/BuscarContenido"
	CatalogoService_FiltrarContenido_FullMethodName    = "/catalogo.v1.CatalogoService/FiltrarContenido"
	CatalogoService_ObtenerDetalle_FullMethodName      = "/catalogo.v1.CatalogoService/ObtenerDetalle"
	CatalogoService_CalificarContenido_FullMethodName  = "/catalogo.v1.CatalogoService/CalificarContenido"
	CatalogoService_CrearContenido_FullMethodName      = "/catalogo.v1.CatalogoService/CrearContenido"
	CatalogoService_ActualizarContenido_FullMethodName = "/catalogo.v1.CatalogoService/ActualizarContenido"
	CatalogoService_EliminarContenido_FullMethodName   = "/catalogo.v1.CatalogoService/EliminarContenido"
)

// CatalogoServiceClient is the client API for CatalogoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogoServiceClient interface {
	// Lectura publica
	ListarContenido(ctx context.Context, in *ListarContenidoRequest, opts ...grpc.CallOption) (*ListarContenidoResponse, error)
	BuscarContenido(ctx context.Context, in *BuscarContenidoRequest, opts ...grpc.CallOption) (*ListarContenidoResponse, error)
	FiltrarContenido(ctx context.Context, in *FiltrarContenidoRequest, opts ...grpc.CallOption) (*ListarContenidoResponse, error)
	ObtenerDetalle(ctx context.Context, in *ObtenerDetalleRequest, opts ...grpc.CallOption) (*ObtenerDetalleResponse, error)
	// Calificacion (perfil autenticado)
	CalificarContenido(ctx context.Context, in *CalificarContenidoRequest, opts ...grpc.CallOption) (*CalificarContenidoResponse, error)
	// Administracion de contenido
	CrearContenido(ctx context.Context, in *CrearContenidoRequest, opts ...grpc.CallOption) (*Contenido, error)
	ActualizarContenido(ctx context.Context, in *ActualizarContenidoRequest, opts ...grpc.CallOption) (*Contenido, error)
	EliminarContenido(ctx context.Context, in *EliminarContenidoRequest, opts ...grpc.CallOption) (*EliminarContenidoResponse, error)
}

type catalogoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogoServiceClient(cc grpc.ClientConnInterface) CatalogoServiceClient {
	return &catalogoServiceClient{cc}
}

func (c *catalogoServiceClient) ListarContenido(ctx context.Context, in *ListarContenidoRequest, opts ...grpc.CallOption) (*ListarContenidoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListarContenidoResponse)
	err := c.cc.Invoke(ctx, CatalogoService_ListarContenido_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogoServiceClient) BuscarContenido(ctx context.Context, in *BuscarContenidoRequest, opts ...grpc.CallOption) (*ListarContenidoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListarContenidoResponse)
	err := c.cc.Invoke(ctx, CatalogoService_BuscarContenido_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogoServiceClient) FiltrarContenido(ctx context.Context, in *FiltrarContenidoRequest, opts ...grpc.CallOption) (*ListarContenidoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListarContenidoResponse)
	err := c.cc.Invoke(ctx, CatalogoService_FiltrarContenido_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogoServiceClient) ObtenerDetalle(ctx context.Context, in *ObtenerDetalleRequest, opts ...grpc.CallOption) (*ObtenerDetalleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObtenerDetalleResponse)
	err := c.cc.Invoke(ctx, CatalogoService_ObtenerDetalle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogoServiceClient) CalificarContenido(ctx context.Context, in *CalificarContenidoRequest, opts ...grpc.CallOption) (*CalificarContenidoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalificarContenidoResponse)
	err := c.cc.Invoke(ctx, CatalogoService_CalificarContenido_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogoServiceClient) CrearContenido(ctx context.Context, in *CrearContenidoRequest, opts ...grpc.CallOption) (*Contenido, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Contenido)
	err := c.cc.Invoke(ctx, CatalogoService_CrearContenido_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogoServiceClient) ActualizarContenido(ctx context.Context, in *ActualizarContenidoRequest, opts ...grpc.CallOption) (*Contenido, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Contenido)
	err := c.cc.Invoke(ctx, CatalogoService_ActualizarContenido_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogoServiceClient) EliminarContenido(ctx context.Context, in *EliminarContenidoRequest, opts ...grpc.CallOption) (*EliminarContenidoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EliminarContenidoResponse)
	err := c.cc.Invoke(ctx, CatalogoService_EliminarContenido_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogoServiceServer is the server API for CatalogoService service.
// All implementations must embed UnimplementedCatalogoServiceServer
// for forward compatibility.
type CatalogoServiceServer interface {
	// Lectura publica
	ListarContenido(context.Context, *ListarContenidoRequest) (*ListarContenidoResponse, error)
	BuscarContenido(context.Context, *BuscarContenidoRequest) (*ListarContenidoResponse, error)
	FiltrarContenido(context.Context, *FiltrarContenidoRequest) (*ListarContenidoResponse, error)
	ObtenerDetalle(context.Context, *ObtenerDetalleRequest) (*ObtenerDetalleResponse, error)
	// Calificacion (perfil autenticado)
	CalificarContenido(context.Context, *CalificarContenidoRequest) (*CalificarContenidoResponse, error)
	// Administracion de contenido
	CrearContenido(context.Context, *CrearContenidoRequest) (*Contenido, error)
	ActualizarContenido(context.Context, *ActualizarContenidoRequest) (*Contenido, error)
	EliminarContenido(context.Context, *EliminarContenidoRequest) (*EliminarContenidoResponse, error)
	mustEmbedUnimplementedCatalogoServiceServer()
}

// UnimplementedCatalogoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogoServiceServer struct{}

func (UnimplementedCatalogoServiceServer) ListarContenido(context.Context, *ListarContenidoRequest) (*ListarContenidoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListarContenido not implemented")
}
func (UnimplementedCatalogoServiceServer) BuscarContenido(context.Context, *BuscarContenidoRequest) (*ListarContenidoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuscarContenido not implemented")
}
func (UnimplementedCatalogoServiceServer) FiltrarContenido(context.Context, *FiltrarContenidoRequest) (*ListarContenidoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FiltrarContenido not implemented")
}
func (UnimplementedCatalogoServiceServer) ObtenerDetalle(context.Context, *ObtenerDetalleRequest) (*ObtenerDetalleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerDetalle not implemented")
}
func (UnimplementedCatalogoServiceServer) CalificarContenido(context.Context, *CalificarContenidoRequest) (*CalificarContenidoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalificarContenido not implemented")
}
func (UnimplementedCatalogoServiceServer) CrearContenido(context.Context, *CrearContenidoRequest) (*Contenido, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearContenido not implemented")
}
func (UnimplementedCatalogoServiceServer) ActualizarContenido(context.Context, *ActualizarContenidoRequest) (*Contenido, error) {
	return nil, status.Error(codes.Unimplemented, "method ActualizarContenido not implemented")
}
func (UnimplementedCatalogoServiceServer) EliminarContenido(context.Context, *EliminarContenidoRequest) (*EliminarContenidoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EliminarContenido not implemented")
}
func (UnimplementedCatalogoServiceServer) mustEmbedUnimplementedCatalogoServiceServer() {}
func (UnimplementedCatalogoServiceServer) testEmbeddedByValue()                         {}

// UnsafeCatalogoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogoServiceServer will
// result in compilation errors.
type UnsafeCatalogoServiceServer interface {
	mustEmbedUnimplementedCatalogoServiceServer()
}

func RegisterCatalogoServiceServer(s grpc.ServiceRegistrar, srv CatalogoServiceServer) {
	// If the following call panics, it indicates UnimplementedCatalogoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogoService_ServiceDesc, srv)
}

func _CatalogoService_ListarContenido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListarContenidoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogoServiceServer).ListarContenido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogoService_ListarContenido_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogoServiceServer).ListarContenido(ctx, req.(*ListarContenidoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogoService_BuscarContenido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuscarContenidoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogoServiceServer).BuscarContenido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogoService_BuscarContenido_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogoServiceServer).BuscarContenido(ctx, req.(*BuscarContenidoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogoService_FiltrarContenido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FiltrarContenidoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogoServiceServer).FiltrarContenido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogoService_FiltrarContenido_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogoServiceServer).FiltrarContenido(ctx, req.(*FiltrarContenidoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogoService_ObtenerDetalle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtenerDetalleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogoServiceServer).ObtenerDetalle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogoService_ObtenerDetalle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogoServiceServer).ObtenerDetalle(ctx, req.(*ObtenerDetalleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogoService_CalificarContenido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalificarContenidoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogoServiceServer).CalificarContenido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogoService_CalificarContenido_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogoServiceServer).CalificarContenido(ctx, req.(*CalificarContenidoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogoService_CrearContenido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearContenidoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogoServiceServer).CrearContenido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogoService_CrearContenido_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogoServiceServer).CrearContenido(ctx, req.(*CrearContenidoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogoService_ActualizarContenido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActualizarContenidoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogoServiceServer).ActualizarContenido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogoService_ActualizarContenido_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogoServiceServer).ActualizarContenido(ctx, req.(*ActualizarContenidoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogoService_EliminarContenido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EliminarContenidoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogoServiceServer).EliminarContenido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogoService_EliminarContenido_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogoServiceServer).EliminarContenido(ctx, req.(*EliminarContenidoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogoService_ServiceDesc is the grpc.ServiceDesc for CatalogoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalogo.v1.CatalogoService",
	HandlerType: (*CatalogoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListarContenido",
			Handler:    _CatalogoService_ListarContenido_Handler,
		},
		{
			MethodName: "BuscarContenido",
			Handler:    _CatalogoService_BuscarContenido_Handler,
		},
		{
			MethodName: "FiltrarContenido",
			Handler:    _CatalogoService_FiltrarContenido_Handler,
		},
		{
			MethodName: "ObtenerDetalle",
			Handler:    _CatalogoService_ObtenerDetalle_Handler,
		},
		{
			MethodName: "CalificarContenido",
			Handler:    _CatalogoService_CalificarContenido_Handler,
		},
		{
			MethodName: "CrearContenido",
			Handler:    _CatalogoService_CrearContenido_Handler,
		},
		{
			MethodName: "ActualizarContenido",
			Handler:    _CatalogoService_ActualizarContenido_Handler,
		},
		{
			MethodName: "EliminarContenido",
			Handler:    _CatalogoService_EliminarContenido_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalogo/v1/catalogo.proto",
}
