from typing import Protocol

from app.domain.models import Plan, Subscription


class PlanRepository(Protocol):
    def create(self, plan: Plan) -> Plan: ...

    def list_active(self) -> list[Plan]: ...

    def get_by_id(self, plan_id: str) -> Plan | None: ...


class SubscriptionRepository(Protocol):
    def create(self, subscription: Subscription) -> Subscription: ...

    def get_active_by_account_id(self, account_id: str) -> Subscription | None: ...

    def get_by_id(self, subscription_id: str) -> Subscription | None: ...

    def update(self, subscription: Subscription) -> Subscription: ...
