// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: notificaciones/v1/notificaciones.proto

package notificacionesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificacionesService_EnviarConfirmacionRegistro_FullMethodName   = "/notificaciones.v1.NotificacionesService/EnviarConfirmacionRegistro"
	NotificacionesService_EnviarRecibo_FullMethodName                 = "/notificaciones.v1.NotificacionesService/EnviarRecibo"
	NotificacionesService_EnviarAlertaNuevaPublicacion_FullMethodName = "/notificaciones.v1.NotificacionesService/EnviarAlertaNuevaPublicacion"
)

// NotificacionesServiceClient is the client API for NotificacionesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificacionesServiceClient interface {
	EnviarConfirmacionRegistro(ctx context.Context, in *ConfirmacionRegistroRequest, opts ...grpc.CallOption) (*NotificacionResponse, error)
	EnviarRecibo(ctx context.Context, in *ReciboRequest, opts ...grpc.CallOption) (*NotificacionResponse, error)
	EnviarAlertaNuevaPublicacion(ctx context.Context, in *AlertaPublicacionRequest, opts ...grpc.CallOption) (*NotificacionResponse, error)
}

type notificacionesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificacionesServiceClient(cc grpc.ClientConnInterface) NotificacionesServiceClient {
	return &notificacionesServiceClient{cc}
}

func (c *notificacionesServiceClient) EnviarConfirmacionRegistro(ctx context.Context, in *ConfirmacionRegistroRequest, opts ...grpc.CallOption) (*NotificacionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificacionResponse)
	err := c.cc.Invoke(ctx, NotificacionesService_EnviarConfirmacionRegistro_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificacionesServiceClient) EnviarRecibo(ctx context.Context, in *ReciboRequest, opts ...grpc.CallOption) (*NotificacionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificacionResponse)
	err := c.cc.Invoke(ctx, NotificacionesService_EnviarRecibo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificacionesServiceClient) EnviarAlertaNuevaPublicacion(ctx context.Context, in *AlertaPublicacionRequest, opts ...grpc.CallOption) (*NotificacionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificacionResponse)
	err := c.cc.Invoke(ctx, NotificacionesService_EnviarAlertaNuevaPublicacion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificacionesServiceServer is the server API for NotificacionesService service.
// All implementations must embed UnimplementedNotificacionesServiceServer
// for forward compatibility.
type NotificacionesServiceServer interface {
	EnviarConfirmacionRegistro(context.Context, *ConfirmacionRegistroRequest) (*NotificacionResponse, error)
	EnviarRecibo(context.Context, *ReciboRequest) (*NotificacionResponse, error)
	EnviarAlertaNuevaPublicacion(context.Context, *AlertaPublicacionRequest) (*NotificacionResponse, error)
	mustEmbedUnimplementedNotificacionesServiceServer()
}

// UnimplementedNotificacionesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificacionesServiceServer struct{}

func (UnimplementedNotificacionesServiceServer) EnviarConfirmacionRegistro(context.Context, *ConfirmacionRegistroRequest) (*NotificacionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnviarConfirmacionRegistro not implemented")
}
func (UnimplementedNotificacionesServiceServer) EnviarRecibo(context.Context, *ReciboRequest) (*NotificacionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnviarRecibo not implemented")
}
func (UnimplementedNotificacionesServiceServer) EnviarAlertaNuevaPublicacion(context.Context, *AlertaPublicacionRequest) (*NotificacionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnviarAlertaNuevaPublicacion not implemented")
}
func (UnimplementedNotificacionesServiceServer) mustEmbedUnimplementedNotificacionesServiceServer() {}
func (UnimplementedNotificacionesServiceServer) testEmbeddedByValue()                               {}

// UnsafeNotificacionesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificacionesServiceServer will
// result in compilation errors.
type UnsafeNotificacionesServiceServer interface {
	mustEmbedUnimplementedNotificacionesServiceServer()
}

func RegisterNotificacionesServiceServer(s grpc.ServiceRegistrar, srv NotificacionesServiceServer) {
	// If the following call panics, it indicates UnimplementedNotificacionesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificacionesService_ServiceDesc, srv)
}

func _NotificacionesService_EnviarConfirmacionRegistro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmacionRegistroRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificacionesServiceServer).EnviarConfirmacionRegistro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificacionesService_EnviarConfirmacionRegistro_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificacionesServiceServer).EnviarConfirmacionRegistro(ctx, req.(*ConfirmacionRegistroRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificacionesService_EnviarRecibo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReciboRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificacionesServiceServer).EnviarRecibo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificacionesService_EnviarRecibo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificacionesServiceServer).EnviarRecibo(ctx, req.(*ReciboRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificacionesService_EnviarAlertaNuevaPublicacion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertaPublicacionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificacionesServiceServer).EnviarAlertaNuevaPublicacion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificacionesService_EnviarAlertaNuevaPublicacion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificacionesServiceServer).EnviarAlertaNuevaPublicacion(ctx, req.(*AlertaPublicacionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificacionesService_ServiceDesc is the grpc.ServiceDesc for NotificacionesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificacionesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notificaciones.v1.NotificacionesService",
	HandlerType: (*NotificacionesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnviarConfirmacionRegistro",
			Handler:    _NotificacionesService_EnviarConfirmacionRegistro_Handler,
		},
		{
			MethodName: "EnviarRecibo",
			Handler:    _NotificacionesService_EnviarRecibo_Handler,
		},
		{
			MethodName: "EnviarAlertaNuevaPublicacion",
			Handler:    _NotificacionesService_EnviarAlertaNuevaPublicacion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notificaciones/v1/notificaciones.proto",
}
