// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: notificaciones/v1/notificaciones.proto

package notificacionesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfirmacionRegistroRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorreoDestino string                 `protobuf:"bytes,1,opt,name=correo_destino,json=correoDestino,proto3" json:"correo_destino,omitempty"`
	NombreUsuario string                 `protobuf:"bytes,2,opt,name=nombre_usuario,json=nombreUsuario,proto3" json:"nombre_usuario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmacionRegistroRequest) Reset() {
	*x = ConfirmacionRegistroRequest{}
	mi := &file_notificaciones_v1_notificaciones_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmacionRegistroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmacionRegistroRequest) ProtoMessage() {}

func (x *ConfirmacionRegistroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notificaciones_v1_notificaciones_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmacionRegistroRequest.ProtoReflect.Descriptor instead.
func (*ConfirmacionRegistroRequest) Descriptor() ([]byte, []int) {
	return file_notificaciones_v1_notificaciones_proto_rawDescGZIP(), []int{0}
}

func (x *ConfirmacionRegistroRequest) GetCorreoDestino() string {
	if x != nil {
		return x.CorreoDestino
	}
	return ""
}

func (x *ConfirmacionRegistroRequest) GetNombreUsuario() string {
	if x != nil {
		return x.NombreUsuario
	}
	return ""
}

type ReciboRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CorreoDestino   string                 `protobuf:"bytes,1,opt,name=correo_destino,json=correoDestino,proto3" json:"correo_destino,omitempty"`
	NombreUsuario   string                 `protobuf:"bytes,2,opt,name=nombre_usuario,json=nombreUsuario,proto3" json:"nombre_usuario,omitempty"`
	IdTransaccion   string                 `protobuf:"bytes,3,opt,name=id_transaccion,json=idTransaccion,proto3" json:"id_transaccion,omitempty"`
	DescripcionPlan string                 `protobuf:"bytes,4,opt,name=descripcion_plan,json=descripcionPlan,proto3" json:"descripcion_plan,omitempty"`
	Monto           float64                `protobuf:"fixed64,5,opt,name=monto,proto3" json:"monto,omitempty"`
	Moneda          string                 `protobuf:"bytes,6,opt,name=moneda,proto3" json:"moneda,omitempty"`
	Fecha           string                 `protobuf:"bytes,7,opt,name=fecha,proto3" json:"fecha,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReciboRequest) Reset() {
	*x = ReciboRequest{}
	mi := &file_notificaciones_v1_notificaciones_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReciboRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReciboRequest) ProtoMessage() {}

func (x *ReciboRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notificaciones_v1_notificaciones_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReciboRequest.ProtoReflect.Descriptor instead.
func (*ReciboRequest) Descriptor() ([]byte, []int) {
	return file_notificaciones_v1_notificaciones_proto_rawDescGZIP(), []int{1}
}

func (x *ReciboRequest) GetCorreoDestino() string {
	if x != nil {
		return x.CorreoDestino
	}
	return ""
}

func (x *ReciboRequest) GetNombreUsuario() string {
	if x != nil {
		return x.NombreUsuario
	}
	return ""
}

func (x *ReciboRequest) GetIdTransaccion() string {
	if x != nil {
		return x.IdTransaccion
	}
	return ""
}

func (x *ReciboRequest) GetDescripcionPlan() string {
	if x != nil {
		return x.DescripcionPlan
	}
	return ""
}

func (x *ReciboRequest) GetMonto() float64 {
	if x != nil {
		return x.Monto
	}
	return 0
}

func (x *ReciboRequest) GetMoneda() string {
	if x != nil {
		return x.Moneda
	}
	return ""
}

func (x *ReciboRequest) GetFecha() string {
	if x != nil {
		return x.Fecha
	}
	return ""
}

type AlertaPublicacionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CorreosDestino  []string               `protobuf:"bytes,1,rep,name=correos_destino,json=correosDestino,proto3" json:"correos_destino,omitempty"`
	TituloContenido string                 `protobuf:"bytes,2,opt,name=titulo_contenido,json=tituloContenido,proto3" json:"titulo_contenido,omitempty"`
	TipoContenido   string                 `protobuf:"bytes,3,opt,name=tipo_contenido,json=tipoContenido,proto3" json:"tipo_contenido,omitempty"` // "pelicula" | "serie"
	Descripcion     string                 `protobuf:"bytes,4,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AlertaPublicacionRequest) Reset() {
	*x = AlertaPublicacionRequest{}
	mi := &file_notificaciones_v1_notificaciones_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertaPublicacionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertaPublicacionRequest) ProtoMessage() {}

func (x *AlertaPublicacionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notificaciones_v1_notificaciones_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertaPublicacionRequest.ProtoReflect.Descriptor instead.
func (*AlertaPublicacionRequest) Descriptor() ([]byte, []int) {
	return file_notificaciones_v1_notificaciones_proto_rawDescGZIP(), []int{2}
}

func (x *AlertaPublicacionRequest) GetCorreosDestino() []string {
	if x != nil {
		return x.CorreosDestino
	}
	return nil
}

func (x *AlertaPublicacionRequest) GetTituloContenido() string {
	if x != nil {
		return x.TituloContenido
	}
	return ""
}

func (x *AlertaPublicacionRequest) GetTipoContenido() string {
	if x != nil {
		return x.TipoContenido
	}
	return ""
}

func (x *AlertaPublicacionRequest) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

type NotificacionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Enviado        bool                   `protobuf:"varint,1,opt,name=enviado,proto3" json:"enviado,omitempty"`
	Mensaje        string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	NotificacionId string                 `protobuf:"bytes,3,opt,name=notificacion_id,json=notificacionId,proto3" json:"notificacion_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificacionResponse) Reset() {
	*x = NotificacionResponse{}
	mi := &file_notificaciones_v1_notificaciones_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificacionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificacionResponse) ProtoMessage() {}

func (x *NotificacionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notificaciones_v1_notificaciones_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificacionResponse.ProtoReflect.Descriptor instead.
func (*NotificacionResponse) Descriptor() ([]byte, []int) {
	return file_notificaciones_v1_notificaciones_proto_rawDescGZIP(), []int{3}
}

func (x *NotificacionResponse) GetEnviado() bool {
	if x != nil {
		return x.Enviado
	}
	return false
}

func (x *NotificacionResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *NotificacionResponse) GetNotificacionId() string {
	if x != nil {
		return x.NotificacionId
	}
	return ""
}

var File_notificaciones_v1_notificaciones_proto protoreflect.FileDescriptor

const file_notificaciones_v1_notificaciones_proto_rawDesc = "" +
	"\n" +
	"&notificaciones/v1/notificaciones.proto\x12\x11notificaciones.v1\"k\n" +
	"\x1bConfirmacionRegistroRequest\x12%\n" +
	"\x0ecorreo_destino\x18\x01 \x01(\tR\rcorreoDestino\x12%\n" +
	"\x0enombre_usuario\x18\x02 \x01(\tR\rnombreUsuario\"\xf3\x01\n" +
	"\rReciboRequest\x12%\n" +
	"\x0ecorreo_destino\x18\x01 \x01(\tR\rcorreoDestino\x12%\n" +
	"\x0enombre_usuario\x18\x02 \x01(\tR\rnombreUsuario\x12%\n" +
	"\x0eid_transaccion\x18\x03 \x01(\tR\ridTransaccion\x12)\n" +
	"\x10descripcion_plan\x18\x04 \x01(\tR\x0fdescripcionPlan\x12\x14\n" +
	"\x05monto\x18\x05 \x01(\x01R\x05monto\x12\x16\n" +
	"\x06moneda\x18\x06 \x01(\tR\x06moneda\x12\x14\n" +
	"\x05fecha\x18\a \x01(\tR\x05fecha\"\xb7\x01\n" +
	"\x18AlertaPublicacionRequest\x12'\n" +
	"\x0fcorreos_destino\x18\x01 \x03(\tR\x0ecorreosDestino\x12)\n" +
	"\x10titulo_contenido\x18\x02 \x01(\tR\x0ftituloContenido\x12%\n" +
	"\x0etipo_contenido\x18\x03 \x01(\tR\rtipoContenido\x12 \n" +
	"\vdescripcion\x18\x04 \x01(\tR\vdescripcion\"s\n" +
	"\x14NotificacionResponse\x12\x18\n" +
	"\aenviado\x18\x01 \x01(\bR\aenviado\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12'\n" +
	"\x0fnotificacion_id\x18\x03 \x01(\tR\x0enotificacionId2\xdf\x02\n" +
	"\x15NotificacionesService\x12u\n" +
	"\x1aEnviarConfirmacionRegistro\x12..notificaciones.v1.ConfirmacionRegistroRequest\x1a'.notificaciones.v1.NotificacionResponse\x12Y\n" +
	"\fEnviarRecibo\x12 .notificaciones.v1.ReciboRequest\x1a'.notificaciones.v1.NotificacionResponse\x12t\n" +
	"\x1cEnviarAlertaNuevaPublicacion\x12+.notificaciones.v1.AlertaPublicacionRequest\x1a'.notificaciones.v1.NotificacionResponseBGZEquetzaltv/services/catalogo/pkg/pb/notificaciones/v1;notificacionesv1b\x06proto3"

var (
	file_notificaciones_v1_notificaciones_proto_rawDescOnce sync.Once
	file_notificaciones_v1_notificaciones_proto_rawDescData []byte
)

func file_notificaciones_v1_notificaciones_proto_rawDescGZIP() []byte {
	file_notificaciones_v1_notificaciones_proto_rawDescOnce.Do(func() {
		file_notificaciones_v1_notificaciones_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notificaciones_v1_notificaciones_proto_rawDesc), len(file_notificaciones_v1_notificaciones_proto_rawDesc)))
	})
	return file_notificaciones_v1_notificaciones_proto_rawDescData
}

var file_notificaciones_v1_notificaciones_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_notificaciones_v1_notificaciones_proto_goTypes = []any{
	(*ConfirmacionRegistroRequest)(nil), // 0: notificaciones.v1.ConfirmacionRegistroRequest
	(*ReciboRequest)(nil),               // 1: notificaciones.v1.ReciboRequest
	(*AlertaPublicacionRequest)(nil),    // 2: notificaciones.v1.AlertaPublicacionRequest
	(*NotificacionResponse)(nil),        // 3: notificaciones.v1.NotificacionResponse
}
var file_notificaciones_v1_notificaciones_proto_depIdxs = []int32{
	0, // 0: notificaciones.v1.NotificacionesService.EnviarConfirmacionRegistro:input_type -> notificaciones.v1.ConfirmacionRegistroRequest
	1, // 1: notificaciones.v1.NotificacionesService.EnviarRecibo:input_type -> notificaciones.v1.ReciboRequest
	2, // 2: notificaciones.v1.NotificacionesService.EnviarAlertaNuevaPublicacion:input_type -> notificaciones.v1.AlertaPublicacionRequest
	3, // 3: notificaciones.v1.NotificacionesService.EnviarConfirmacionRegistro:output_type -> notificaciones.v1.NotificacionResponse
	3, // 4: notificaciones.v1.NotificacionesService.EnviarRecibo:output_type -> notificaciones.v1.NotificacionResponse
	3, // 5: notificaciones.v1.NotificacionesService.EnviarAlertaNuevaPublicacion:output_type -> notificaciones.v1.NotificacionResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notificaciones_v1_notificaciones_proto_init() }
func file_notificaciones_v1_notificaciones_proto_init() {
	if File_notificaciones_v1_notificaciones_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notificaciones_v1_notificaciones_proto_rawDesc), len(file_notificaciones_v1_notificaciones_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notificaciones_v1_notificaciones_proto_goTypes,
		DependencyIndexes: file_notificaciones_v1_notificaciones_proto_depIdxs,
		MessageInfos:      file_notificaciones_v1_notificaciones_proto_msgTypes,
	}.Build()
	File_notificaciones_v1_notificaciones_proto = out.File
	file_notificaciones_v1_notificaciones_proto_goTypes = nil
	file_notificaciones_v1_notificaciones_proto_depIdxs = nil
}
