// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: streaming/v1/streaming.proto

package streamingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamingService_ActualizarProgreso_FullMethodName = "/streaming.v1.StreamingService/ActualizarProgreso"
	StreamingService_ObtenerProgreso_FullMethodName    = "/streaming.v1.StreamingService/ObtenerProgreso"
	StreamingService_ObtenerHistorial_FullMethodName   = "/streaming.v1.StreamingService/ObtenerHistorial"
)

// StreamingServiceClient is the client API for StreamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamingServiceClient interface {
	// Guarda o actualiza el progreso de reproduccion
	ActualizarProgreso(ctx context.Context, in *ActualizarProgresoRequest, opts ...grpc.CallOption) (*ActualizarProgresoResponse, error)
	// Devuelve el progreso guardado para reanudar reproduccion
	ObtenerProgreso(ctx context.Context, in *ObtenerProgresoRequest, opts ...grpc.CallOption) (*HistorialReproduccion, error)
	// Devuelve el historial reciente de un perfil
	ObtenerHistorial(ctx context.Context, in *ObtenerHistorialRequest, opts ...grpc.CallOption) (*ObtenerHistorialResponse, error)
}

type streamingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamingServiceClient(cc grpc.ClientConnInterface) StreamingServiceClient {
	return &streamingServiceClient{cc}
}

func (c *streamingServiceClient) ActualizarProgreso(ctx context.Context, in *ActualizarProgresoRequest, opts ...grpc.CallOption) (*ActualizarProgresoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActualizarProgresoResponse)
	err := c.cc.Invoke(ctx, StreamingService_ActualizarProgreso_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamingServiceClient) ObtenerProgreso(ctx context.Context, in *ObtenerProgresoRequest, opts ...grpc.CallOption) (*HistorialReproduccion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistorialReproduccion)
	err := c.cc.Invoke(ctx, StreamingService_ObtenerProgreso_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamingServiceClient) ObtenerHistorial(ctx context.Context, in *ObtenerHistorialRequest, opts ...grpc.CallOption) (*ObtenerHistorialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObtenerHistorialResponse)
	err := c.cc.Invoke(ctx, StreamingService_ObtenerHistorial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamingServiceServer is the server API for StreamingService service.
// All implementations must embed UnimplementedStreamingServiceServer
// for forward compatibility.
type StreamingServiceServer interface {
	// Guarda o actualiza el progreso de reproduccion
	ActualizarProgreso(context.Context, *ActualizarProgresoRequest) (*ActualizarProgresoResponse, error)
	// Devuelve el progreso guardado para reanudar reproduccion
	ObtenerProgreso(context.Context, *ObtenerProgresoRequest) (*HistorialReproduccion, error)
	// Devuelve el historial reciente de un perfil
	ObtenerHistorial(context.Context, *ObtenerHistorialRequest) (*ObtenerHistorialResponse, error)
	mustEmbedUnimplementedStreamingServiceServer()
}

// UnimplementedStreamingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamingServiceServer struct{}

func (UnimplementedStreamingServiceServer) ActualizarProgreso(context.Context, *ActualizarProgresoRequest) (*ActualizarProgresoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActualizarProgreso not implemented")
}
func (UnimplementedStreamingServiceServer) ObtenerProgreso(context.Context, *ObtenerProgresoRequest) (*HistorialReproduccion, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerProgreso not implemented")
}
func (UnimplementedStreamingServiceServer) ObtenerHistorial(context.Context, *ObtenerHistorialRequest) (*ObtenerHistorialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerHistorial not implemented")
}
func (UnimplementedStreamingServiceServer) mustEmbedUnimplementedStreamingServiceServer() {}
func (UnimplementedStreamingServiceServer) testEmbeddedByValue()                          {}

// UnsafeStreamingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamingServiceServer will
// result in compilation errors.
type UnsafeStreamingServiceServer interface {
	mustEmbedUnimplementedStreamingServiceServer()
}

func RegisterStreamingServiceServer(s grpc.ServiceRegistrar, srv StreamingServiceServer) {
	// If the following call panics, it indicates UnimplementedStreamingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamingService_ServiceDesc, srv)
}

func _StreamingService_ActualizarProgreso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActualizarProgresoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamingServiceServer).ActualizarProgreso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamingService_ActualizarProgreso_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamingServiceServer).ActualizarProgreso(ctx, req.(*ActualizarProgresoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamingService_ObtenerProgreso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtenerProgresoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamingServiceServer).ObtenerProgreso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamingService_ObtenerProgreso_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamingServiceServer).ObtenerProgreso(ctx, req.(*ObtenerProgresoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamingService_ObtenerHistorial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtenerHistorialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamingServiceServer).ObtenerHistorial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamingService_ObtenerHistorial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamingServiceServer).ObtenerHistorial(ctx, req.(*ObtenerHistorialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamingService_ServiceDesc is the grpc.ServiceDesc for StreamingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streaming.v1.StreamingService",
	HandlerType: (*StreamingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActualizarProgreso",
			Handler:    _StreamingService_ActualizarProgreso_Handler,
		},
		{
			MethodName: "ObtenerProgreso",
			Handler:    _StreamingService_ObtenerProgreso_Handler,
		},
		{
			MethodName: "ObtenerHistorial",
			Handler:    _StreamingService_ObtenerHistorial_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "streaming/v1/streaming.proto",
}
